CREATE TABLE IF NOT EXISTS "users" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "email" varchar,
                         "login" varchar,
                         "name" varchar,
                         "birthday" date
);

CREATE TABLE IF NOT EXISTS "films" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "description" varchar,
                         "release_date" date,
                         "duration" integer,
                         "rate" integer,
                         "rating_mpa" integer
);

CREATE TABLE IF NOT EXISTS "genre_type" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" varchar
);

CREATE TABLE IF NOT EXISTS "film_genre" (
                                       "film_id" integer,
                                       "genre_id" integer
);

CREATE TABLE IF NOT EXISTS "rating_mpa" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" varchar
);

CREATE TABLE IF NOT EXISTS "likes" (
                         "film_id" integer,
                         "user_id" integer
);

CREATE TABLE IF NOT EXISTS "relationship" (
                                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "user_id" integer,
                                "friend_id" integer,
                                "relationship_status" boolean
);

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre_type" ("id");

ALTER TABLE "relationship" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id");

ALTER TABLE "relationship" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "films" ADD FOREIGN KEY ("rating_mpa") REFERENCES "rating_mpa" ("id");

