CREATE TABLE IF NOT EXISTS "user" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "email" varchar,
                         "login" varchar,
                         "name" varchar,
                         "birthday" date
);

CREATE TABLE IF NOT EXISTS "film" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "description" varchar,
                         "release_date" date,
                         "duration" integer,
                         "rate" integer,
                         "rating_mpa" integer
);

CREATE TABLE IF NOT EXISTS "genre_type" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" varchar
);

CREATE TABLE IF NOT EXISTS "film_genre" (
                                       "film_id" integer,
                                       "genre_id" integer,
                                        PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE IF NOT EXISTS "rating_mpa" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" varchar
);

CREATE TABLE IF NOT EXISTS "like" (
                         "film_id" integer,
                         "user_id" integer,
                          PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "relationship" (
                                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "user_id" integer,
                                "friend_id" integer,
                                "relationship_status" boolean
);

ALTER TABLE "like" ADD FOREIGN KEY ("film_id") REFERENCES "film" ("id");

ALTER TABLE "like" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("film_id") REFERENCES "film" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre_type" ("id");

ALTER TABLE "relationship" ADD FOREIGN KEY ("friend_id") REFERENCES "user" ("id");

ALTER TABLE "relationship" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "film" ADD FOREIGN KEY ("rating_mpa") REFERENCES "rating_mpa" ("id");

